services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://pgdb:5432/ebook_app
#    env_file:
#      - path: .env
#        required: true
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: pgdb
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ebook_app
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: